export const CATEGORIZED_SKILLS = [
    {
      title: 'Programming Languages',
      skills: [
        'c',
        'cplusplus',
        'csharp',
        'go',
        'java',
        'javascript',
        'typescript',
        'php',
        'perl',
        'ruby',
        'scala',
        'python',
        'swift',
        'objectivec',
        'clojure',
        'rust',
        'haskell',
        'coffeescript',
        'elixir',
        'erlang',
        'nim',
      ],
    },
    {
      title: 'Frontend Development',
      skills: [
        'vuejs',
        'react',
        'svelte',
        'angularjs',
        'angular',
        'backbonejs',
        'bootstrap',
        'vuetify',
        'css3',
        'html5',
        'pug',
        'gulp',
        'sass',
        'redux',
        'webpack',
        'babel',
        'tailwind',
        'materialize',
        'bulma',
        'gtk',
        'qt',
        'wx_widgets',
        'ember',
      ],
    },
    {
      title: 'Backend Development',
      skills: [
        'nodejs',
        'spring',
        'express',
        'graphql',
        'kafka',
        'solr',
        'rabbitMQ',
        'hadoop',
        'nginx',
        'openresty',
        'nestjs',
      ],
    },
    {
      title: 'Mobile App Development',
      skills: [
        'android',
        'flutter',
        'dart',
        'kotlin',
        'nativescript',
        'xamarin',
        'reactnative',
        'ionic',
        'apachecordova',
      ],
    },
    {
      title: 'AI/ML',
      skills: ['tensorflow', 'pytorch', 'pandas', 'seaborn', 'opencv', 'scikit_learn'],
    },
    {
      title: 'Database',
      skills: [
        'mongodb',
        'mysql',
        'postgresql',
        'redis',
        'oracle',
        'cassandra',
        'couchdb',
        'hive',
        'realm',
        'mariadb',
        'cockroachdb',
        'elasticsearch',
        'sqlite',
        'mssql',
      ],
    },
    {
      title: 'Data Visualization',
      skills: ['d3js', 'chartjs', 'canvasjs', 'kibana', 'grafana'],
    },
    {
      title: 'Devops',
      skills: ['aws', 'docker', 'jenkins', 'gcp', 'kubernetes', 'bash', 'azure', 'vagrant', 'circleci', 'travisci'],
    },
    {
      title: 'Backend as a Service(BaaS)',
      skills: ['firebase', 'appwrite', 'amplify', 'heroku'],
    },
    {
      title: 'Framework',
      skills: ['django', 'dotnet', 'electron', 'symfony', 'laravel', 'codeigniter', 'rails', 'flask', 'quasar'],
    },
    {
      title: 'Testing',
      skills: ['cypress', 'selenium', 'jest', 'mocha', 'puppeteer', 'karma', 'jasmine'],
    },
    {
      title: 'Software',
      skills: ['illustrator', 'photoshop', 'xd', 'figma', 'blender', 'sketch', 'invision', 'framer', 'matlab', 'postman'],
    },
    {
      title: 'Static Site Generators',
      skills: [
        'gatsby',
        'gridsome',
        'hugo',
        'jekyll',
        'nextjs',
        'nuxtjs',
        '11ty',
        'scully',
        'sculpin',
        'sapper',
        'vuepress',
        'hexo',
        'middleman',
      ],
    },
    {
      title: 'Game Engines',
      skills: ['unity', 'unreal'],
    },
    {
      title: 'Automation',
      skills: ['zapier', 'ifttt'],
    },
    {
      title: 'Other',
      skills: ['linux', 'git', 'arduino'],
    },
];
  

  