export const WEBSITES: {[name: string]: string} = {
  facebook: 'https://www.facebook.com/',
  twitter: 'https://www.twitter.com/',
  linkedin: 'https://www.linkedin.com/',
  instagram: 'https://www.instagram.com/',
  reddit: 'https://www.reddit.com/',
  stackoverflow: 'https://www.stackoverflow.com/',
  dribbble: 'https://www.dribbble.com/',
  behance: 'https://www.behance.net/',
  'dev.to': 'https://dev.to',
  codepen: 'https://codepen.io/',
  codesandbox: 'https://codesandbox.io/',
  hackerrank: 'https://www.hackerrank.com/',
  leetcode: 'https://leetcode.com/',
  topcoder: 'https://www.topcoder.com/',
  medium: 'https://www.medium.com/',
  discord: 'https://discord.com/',
  youtube: 'https://youtube.com/',
  twitch: 'https://www.twitch.tv/',
  buymeacoffee: 'https://www.buymeacoffee.com/',
  'ko-fi': 'https://www.ko-fi.com/'
};